import { contextBridge, ipcRenderer } from 'electron';

// Expose safe context to the React app
contextBridge.exposeInMainWorld('electron', {
    readDb: () => ipcRenderer.invoke('read-db'),
    writeDb: (data: any) => ipcRenderer.invoke('write-db', data),
    fetchYouTrack: (options: any) => ipcRenderer.invoke('fetch-youtrack', options),
    getExcludedIssues: () => ipcRenderer.invoke('get-excluded-issues'),
    setIssueExcluded: (id: string, excluded: boolean) => ipcRenderer.invoke('set-issue-excluded', { id, excluded }),
    getYoutrackTabs: (projectId: string) => ipcRenderer.invoke('get-youtrack-tabs', projectId),
    saveYoutrackTab: (tab: { id: string; projectId: string; name: string; statuses: string[]; includeFilters?: boolean; orderIndex?: number }) => ipcRenderer.invoke('save-youtrack-tab', tab),
    deleteYoutrackTab: (id: string) => ipcRenderer.invoke('delete-youtrack-tab', id),
    reorderYoutrackTabs: (tabs: { id: string; orderIndex: number }[]) => ipcRenderer.invoke('reorder-youtrack-tabs', tabs),
    getIssueTaskTypes: (issueIds: string[]) => ipcRenderer.invoke('get-issue-task-types', issueIds),
    setIssueTaskType: (issueId: string, taskTypeId: string) => ipcRenderer.invoke('set-issue-task-type', issueId, taskTypeId),
    getWorkItems: (projectId: string) => ipcRenderer.invoke('get-work-items', projectId),
    upsertWorkItems: (data: { items: any[], projectId: string }) => ipcRenderer.invoke('upsert-work-items', data),
    getOrderItemTemplate: (projectId: string) => ipcRenderer.invoke('get-order-item-template', projectId),
    saveOrderItemTemplate: (data: { projectId: string, data: any }) => ipcRenderer.invoke('save-order-item-template', data),
    getIssueCategories: () => ipcRenderer.invoke('get-issue-categories'),
    setIssueCategory: (data: { issueId: string, category: string }) => ipcRenderer.invoke('set-issue-category', data),
    setIssueCategoriesBulk: (data: { issueIds: string[], category: string }) => ipcRenderer.invoke('set-issue-categories-bulk', data),
    importWorkItems: (data: { items: any[], projectId: string }) => ipcRenderer.invoke('import-work-items', data),
    importOrders: (data: { orders: any[], projectId: string }) => ipcRenderer.invoke('import-orders', data),
    getEstimation: (projectId: string) => ipcRenderer.invoke('get-estimation', projectId),
    saveEstimation: (data: { projectId: string, data: any }) => ipcRenderer.invoke('save-estimation', data),
    getMeetingNotes: (projectId: string) => ipcRenderer.invoke('get-meeting-notes', projectId),
    saveMeetingNotes: (data: { projectId: string, data: any }) => ipcRenderer.invoke('save-meeting-notes', data),
    getStatusReports: (projectId: string) => ipcRenderer.invoke('get-status-reports', projectId),
    saveStatusReport: (data: { projectId: string, data: any }) => ipcRenderer.invoke('save-status-report', data),
    deleteStatusReport: (id: string) => ipcRenderer.invoke('delete-status-report', id),
    appendGoogleDoc: (data: { docLink: string, content: string, title: string, participants: string[] }) => ipcRenderer.invoke('append-google-doc', data),
    getGoogleAuthStatus: () => ipcRenderer.invoke('get-google-auth-status'),
    getGoogleAuthUrl: () => ipcRenderer.invoke('get-google-auth-url'),
    authorizeGoogle: (code: string) => ipcRenderer.invoke('authorize-google', code),
    logoutGoogle: () => ipcRenderer.invoke('logout-google'),
    openExternal: (url: string) => ipcRenderer.invoke('open-external', url),
    exportDatabase: () => ipcRenderer.invoke('export-database'),
    importDatabase: () => ipcRenderer.invoke('import-database'),
    exportPdf: (options?: { defaultFileName?: string, password?: string }) => ipcRenderer.invoke('export-pdf', options),
    writeClipboardHtml: (html: string) => ipcRenderer.invoke('write-clipboard-html', html),
    
    // Daily Handlers
    getDailyHubs: () => ipcRenderer.invoke('get-daily-hubs'),
    saveDailyHub: (hub: any) => ipcRenderer.invoke('save-daily-hub', hub),
    deleteDailyHub: (id: string) => ipcRenderer.invoke('delete-daily-hub', id),
    getDailySections: (hubId: string) => ipcRenderer.invoke('get-daily-sections', hubId),
    saveDailySection: (section: any) => ipcRenderer.invoke('save-daily-section', section),
    deleteDailySection: (id: string) => ipcRenderer.invoke('delete-daily-section', id),
    reorderDailySections: (sections: any[]) => ipcRenderer.invoke('reorder-daily-sections', sections),
    getDailyComments: () => ipcRenderer.invoke('get-daily-comments'),
    saveDailyComment: (data: { issueId: string, content: string }) => ipcRenderer.invoke('save-daily-comment', data),
    getDailyIssueStates: () => ipcRenderer.invoke('get-daily-issue-states'),
    saveDailyIssueState: (data: { issueId: string, isCollapsed: boolean }) => ipcRenderer.invoke('save-daily-issue-state', data),
});

