import { format } from 'date-fns';
import { pl } from 'date-fns/locale';
import { Calendar, Clock, ExternalLink, History, MessageSquare, User, X } from 'lucide-react';
import type { IssueWithHistory } from '@/types/youtrack';

export const DailyIssueDetailsModal = ({ issue, isOpen, onClose, dateFrom, dateTo, baseUrl }: { issue: IssueWithHistory; isOpen: boolean; onClose: () => void; dateFrom: string; dateTo: string; baseUrl: string }) => {
  if (!isOpen) return null;
  const fromTime = new Date(`${dateFrom}T00:00:00`).getTime();
  const toTime = new Date(`${dateTo}T23:59:59`).getTime();
  const periodActivities = (issue.timeline || []).filter((entry) => entry.timestamp >= fromTime && entry.timestamp <= toTime).filter((entry) => entry.type === 'comment' || entry.type === 'work-item' || entry.type === 'field-change');
  const olderActivities = (issue.timeline || []).filter((entry) => entry.timestamp < fromTime).filter((entry) => entry.type === 'comment' || entry.type === 'work-item' || entry.type === 'field-change');
  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/60 p-4 backdrop-blur-md" onClick={onClose}>
      <div className="flex max-h-[90vh] w-full max-w-4xl flex-col overflow-hidden rounded-2xl bg-white shadow-2xl dark:bg-gray-900" onClick={(event) => event.stopPropagation()}>
        <div className="flex items-center justify-between border-b bg-gray-50/50 px-6 py-4 dark:border-gray-800 dark:bg-gray-800/30"><div className="flex items-center gap-3"><span className="rounded bg-indigo-100 px-2 py-1 text-xs font-bold tracking-wider text-indigo-700 dark:bg-indigo-900/40 dark:text-indigo-300">{issue.project?.shortName || 'PRJ'}</span><a href={`${baseUrl}/issue/${issue.idReadable}`} target="_blank" rel="noreferrer" className="flex items-center gap-1 font-mono text-sm font-bold text-gray-500 hover:text-indigo-600">{issue.idReadable}<ExternalLink size={14} /></a>{issue.state && <span className="rounded px-2 py-0.5 text-xs font-bold" style={{ backgroundColor: issue.state.color.background, color: issue.state.color.foreground }}>{issue.state.name}</span>}</div><button onClick={onClose} className="rounded-full p-2 text-gray-400 hover:bg-gray-200 dark:hover:bg-gray-700"><X size={20} /></button></div>
        <div className="flex-1 space-y-8 overflow-y-auto p-6">
          <section className="space-y-4"><h2 className="text-2xl font-extrabold text-gray-900 dark:text-white">{issue.summary}</h2><div className="rounded-xl border bg-gray-50 p-4 text-sm leading-relaxed text-gray-700 dark:border-gray-800 dark:bg-gray-800/40 dark:text-gray-300">{issue.description || 'Brak opisu zadania.'}</div></section>
          <div className="grid grid-cols-1 gap-6 md:grid-cols-3"><div className="space-y-4"><h3 className="flex items-center gap-2 border-b pb-2 text-xs font-bold uppercase tracking-widest text-gray-400 dark:border-gray-800"><User size={14} />Przypisanie</h3><p className="text-sm font-bold dark:text-white">{issue.assignee?.fullName || issue.assignee?.name || 'Nieprzypisane'}</p></div><div className="space-y-4"><h3 className="flex items-center gap-2 border-b pb-2 text-xs font-bold uppercase tracking-widest text-gray-400 dark:border-gray-800"><Clock size={14} />Estymacja i czas</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-gray-500 dark:text-gray-400">Estymacja:</span><span className="font-bold dark:text-white">{issue.estimation?.presentation || 'Brak'}</span></div><div className="flex justify-between"><span className="text-gray-500 dark:text-gray-400">Przepracowano:</span><span className="font-bold text-emerald-600 dark:text-emerald-400">{issue.spentTime?.presentation || '0h'}</span></div></div></div><div className="space-y-4"><h3 className="flex items-center gap-2 border-b pb-2 text-xs font-bold uppercase tracking-widest text-gray-400 dark:border-gray-800"><Calendar size={14} />Terminy</h3><div className="space-y-2 text-sm"><div className="flex justify-between"><span className="text-gray-500 dark:text-gray-400">Utworzono:</span><span className="dark:text-gray-300">{issue.created ? format(new Date(issue.created), 'PP', { locale: pl }) : '-'}</span></div>{issue.dueDate && <div className="flex justify-between"><span className="text-gray-500 dark:text-gray-400">Termin (Due):</span><span className="font-bold text-amber-600">{format(new Date(issue.dueDate), 'PP', { locale: pl })}</span></div>}</div></div></div>
          <section className="space-y-4"><h3 className="flex items-center gap-2 border-b pb-2 text-xs font-bold uppercase tracking-widest text-gray-400 dark:border-gray-800"><History size={14} />Historia aktywnoœci</h3><div className="space-y-4">{periodActivities.map((activity) => <div key={activity.id} className="rounded-lg border bg-gray-50 p-3 text-sm dark:border-gray-800 dark:bg-gray-800/30"><div className="mb-1 text-[11px] font-bold text-gray-500 dark:text-gray-400">{activity.author.name} • {format(new Date(activity.timestamp), 'PPP p', { locale: pl })}</div>{activity.type === 'comment' && <div className="flex gap-2 text-gray-700 dark:text-gray-300"><MessageSquare size={14} className="mt-1 shrink-0 text-blue-500" />{activity.text}</div>}{activity.type === 'field-change' && <div className="text-gray-700 dark:text-gray-300"><span className="font-semibold">{activity.field}:</span> {String(activity.removed || 'Brak')} › {String(activity.added || 'Brak')}</div>}{activity.type === 'work-item' && <div className="text-gray-700 dark:text-gray-300">Zalogowano {activity.minutes || 0}m {activity.workComments?.length ? `- ${activity.workComments.join(', ')}` : ''}</div>}</div>)}{periodActivities.length === 0 && <p className="text-sm italic text-gray-500">Brak aktywnoœci w wybranym zakresie dat.</p>}{olderActivities.length > 0 && <details className="rounded-xl border bg-gray-50 p-4 dark:border-gray-800 dark:bg-gray-800/30"><summary className="cursor-pointer text-sm font-semibold text-gray-600 dark:text-gray-300">Poka¿ starsz¹ historiê ({olderActivities.length})</summary><div className="mt-4 space-y-3">{olderActivities.map((activity) => <div key={activity.id} className="text-sm text-gray-600 dark:text-gray-400">{format(new Date(activity.timestamp), 'PPP p', { locale: pl })} • {activity.author.name}</div>)}</div></details>}</div></section>
        </div>
        <div className="flex justify-end border-t bg-gray-50 px-6 py-4 dark:border-gray-800 dark:bg-gray-800/40"><button onClick={onClose} className="rounded-xl bg-indigo-600 px-6 py-2 font-bold text-white hover:bg-indigo-700">Zamknij</button></div>
      </div>
    </div>
  );
};
